server:
  port: 9527

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.atguigu.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true     #访问路径可以显示IP地址

zuul:
  #ignored-services: microservicecloud-dept
  prefix: /lk
  ignored-services: "*"
  routes:
    mydept.serviceId: microservicecloud-depts
    mydept.path: /mdept/**
#   zuul:   
#  routes:     
#  mydept:
#    serviceId: microservicecloud-dept    
#    mydept:
#      path: /mydept/**:

info:
  app.name: microservicecloud-zuul-gateway
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

